---
deployment:
  tasks:
    - export DEPLOYPATH=/home/actlwznc/public_html/with_backend_public/
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/data $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/php $DEPLOYPATH
    - /bin/cp -R public/sounds $DEPLOYPATH
    - /bin/cp -R public/vendors $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/.favicon.ico $DEPLOYPATH
    - /bin/cp public/mix-manifest.json $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
